# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: hjorthjort
email: hjort@hjorthjort.xyz
description: > # this means to ignore newlines until "baseurl:"
    9 days out of 10 I’m a computer scientist, but my background is in “Misc”. Will pretend to be charming and interesting for attention.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hjorthjort.github.io" # the base hostname & protocol for your site
twitter_username: hjortgjort
github_username:  hjorthjort
medium_username: rikardhjort

# Build settings
markdown: kramdown

# Assets
assets:
    sources:
        - assets
        - assets/img
